apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  custom-error-page.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        return 500 "Internal Server Error";
      }
    }