apiVersion: v1
kind: Service
metadata:
  name: ng-service-example
spec:
  selector:
    app: simple-ng
    environment: test
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
