package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    // https://stackoverflow.com/questions/3333611/why-springmvc-request-method-get-not-supported
    // "Apparently some POST requests looks like a "GET" to the server (like Heroku...)"
    // Previously, the below was: @PostMapping, but was keep getting GET not allowed.
    @RequestMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam(name = "name") String name,
                                            @RequestParam(name = "email") String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}