# permissions for end users to edit nginxoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-operator
    app.kubernetes.io/part-of: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxoperator-editor-role
rules:
- apiGroups:
  - operator.example.com
  resources:
  - nginxoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.example.com
  resources:
  - nginxoperators/status
  verbs:
  - get
