# CMake generated Testfile for 
# Source directory: /home/bob/Desktop/FifthPracticeBucket/OpenCVJSPrac/opencv/modules
# Build directory: /home/bob/Desktop/FifthPracticeBucket/OpenCVJSPrac/build_js/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(".firstpass/calib3d")
subdirs(".firstpass/core")
subdirs(".firstpass/dnn")
subdirs(".firstpass/features2d")
subdirs(".firstpass/flann")
subdirs(".firstpass/gapi")
subdirs(".firstpass/highgui")
subdirs(".firstpass/imgcodecs")
subdirs(".firstpass/imgproc")
subdirs(".firstpass/java")
subdirs(".firstpass/js")
subdirs(".firstpass/ml")
subdirs(".firstpass/objdetect")
subdirs(".firstpass/photo")
subdirs(".firstpass/python")
subdirs(".firstpass/stitching")
subdirs(".firstpass/ts")
subdirs(".firstpass/video")
subdirs(".firstpass/videoio")
subdirs(".firstpass/world")
subdirs("core")
subdirs("flann")
subdirs("imgproc")
subdirs("photo")
subdirs("python_tests")
subdirs("dnn")
subdirs("features2d")
subdirs("calib3d")
subdirs("objdetect")
subdirs("video")
subdirs("js")
