package com.example.practicewithdagger

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.example.practicewithdagger.di.ApiService
import com.example.practicewithdagger.di.LocalStore
import com.example.practicewithdagger.di.LoginManager
import com.example.practicewithdagger.di.component.DaggerLoginComponent
// The below is suppose to be generated by Dagger.
// http://mahmoudramadan.me/getting-started-to-dagger-2-with-kotlin-for-android-app-development/
//import com.example.practicewithdagger.di.component.DaggerLoginComponent
import javax.inject.Inject
import kotlin.math.log

class MainActivity : AppCompatActivity() {

    @Inject
    lateinit var  loginManager:LoginManager

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val loginComponent = DaggerLoginComponent.create()
        loginComponent.inject(this)

        loginManager.login("ramadan", "123")
    }
}